name: TimeFold
description: A time modifying plugin
version: 0.2b
author: Silverstar
main: me.silverstar.timefold.TimeFold
commands:
    timefold:
        description: timefold
        usage: /timefold